import COLORS from "./colors";

export const LIGHT = {
  PRIMARY: COLORS.PRIMARY,
  PRIMARY_ALT: COLORS.PRIMARY,
  PAID: COLORS.PAID,
  NOT_RECEIVED: COLORS.NOT_RECEIVED,
  RECEIVED: COLORS.RECEIVED,
  BACKGROUND: COLORS.LIGHT,
  NAVIGATION: COLORS.WHITE,
  TEXT: COLORS.DARK,
  DISABLED: COLORS.GREY,
  CARD: COLORS.WHITE,
  ICONS: COLORS.DARK,
};

export const DARK = {
  PRIMARY: COLORS.PRIMARY_DARK,
  PRIMARY_ALT: COLORS.PRIMARY,
  PAID: COLORS.PAID,
  NOT_RECEIVED: COLORS.NOT_RECEIVED,
  RECEIVED: COLORS.RECEIVED,
  BACKGROUND: COLORS.BLACK,
  NAVIGATION: COLORS.DARK,
  TEXT: COLORS.LIGHT,
  DISABLED: COLORS.GREY_DARK,
  CARD: COLORS.DARK,
  ICONS: COLORS.GREY,
};

const THEME = {
  DARK,
  LIGHT,
};

export const THEME_ENUM = {
  DARK: 0,
  LIGHT: 1,
};

export default THEME;
